### ISSUE TITLE
Multiple images posts error

### ISSUE THREAD

**Issue by Sputnik1996** [Ramenisneat/Community-post-images-scraper#1]
When the scraper finds a post with several images, it downloads the first image from the post repeatedly but only the squared preview, not the entire image.

**Comment by Ramenisneat** [comment]
Oh, I've haven't thought of that edge case. Working on a fix. If you could provide an example channel, that would be helpful.

**Comment by Ramenisneat** [comment]
After some work, it seems to work fine now. Please go ahead and try it out.
P.S. I'm pretty sure that youtube automatically square crops the images on multi-image posts, even when the post is opened separately. That's what I've seen while working on it.
